### PR TITLE
Fix compress error

### PR DESCRIPTION
**Pull request by hayasugihayato**
fix “no implementation for `chrono::datetime::DateTime<chrono::offset::utc::Utc> + time::Duration`” error

### CODE REVIEW

**Comment by wolfnether** [comment]
which rust version do you use?

**Comment by hayasugihayato** [comment]
> which rust version do you use?

rustc 1.73.0 (cc66ad468 2023-10-03)

**Comment by wolfnether** [comment]
that wierd that you have this error
________________________________
De : 速杉ハヤト ***@***.***>
Envoyé : lundi 6 novembre 2023 16:30
À : wolfnether/SimrailStationLoggerOnline ***@***.***>
Cc : wolfnether ***@***.***>; Comment ***@***.***>
Objet : Re: [wolfnether/SimrailStationLoggerOnline] Fix compress error (PR #2)


which rust version do you use?

rustc 1.73.0 (cc66ad468 2023-10-03)

**Comment by hayasugihayato** [comment]
But there are indeed such problems.

**Comment by wolfnether** [comment]
[360bb70](https://github.com/wolfnether/SimrailStationLoggerOnline/commit/360bb7022a50a69a67881bcb8e84dcd6025bc474) had fixed it

**Pull request closed without merging**
